### PR TITLE
Cleanups

### PR DESCRIPTION
**Pull request by oyvindberg**

### CODE REVIEW

**Comment by chandu0101** [comment]
first of all thanks for PR :) 

> package chandu0101.scalajs.react.components
> package listviews

I see package names splitted like this , can you fix them 

> private[components] val JSMacro   = _root_.chandu0101.macros.tojs.JSMacro

remove root...

**Comment by oyvindberg** [comment]
Sure, I can get rid of that patch, think i can get to that later tonight.

For the record, the reason for doing it like this is that a nested package declaration like that opens up the parent package scope to the child package, so everything from there is available without an explicit import. It's a pretty neat semantic way of structuring things, so you have all the generic things (implicit helpers, utils, models) in that parent package, and concrete code you write directly inherits it all. The other added bonus is a reduced list of imports, so you can see the «real», external dependencies for a given module easier. 

Anyhow, it doesn't matter for this project, it's just my preferred way of structuring, so i figured i would see if you liked it :)

**Comment by chandu0101** [comment]
oh wait 

> the reason for doing it like this is that a nested package declaration like that opens up the parent package scope to the child package, so everything from there is available without an explicit import

neat :+1:  , i didn't know that probably i should have asked why instead of dictating to remove :( , don't revert back just keep as is. just remove that root fix :)

**Comment by oyvindberg** [comment]
ahaha ok, aalmost good timing there - i was five minutes into reverting it. Rebasing on master and pushing here soon

**Comment by chandu0101** [comment]
LGTM , learned new techniques, thank you  :)

**Pull request merged**
