### PR TITLE
Selectable table

### PR DESCRIPTION
**Pull request by atooni**
React Table now has an optional selection mode. In selection mode, one can choose whether multi selects are enabled. When multiselects are enabled, a "select all" checkbox in the table header can be activated as well. 

Minor issues with inconsistencies in sort after search text has changed have been fixed. 
Minor issue that sort wouldn't go back to ASC after DSC has been fixed. 

Finally, some use case have graphical cell renderers and the values can't be sorted reasonably. Now the ordering on a column can be optional and only the columns that have an ordering defined will allow to apply a sort. 

Also, the display of the settings bar to change the page size is now optional.

New example page for Table with Selections has been added.

### CODE REVIEW

**Comment by rleibman** [comment]
Wow, lots of changes and good stuff. I didn't read it all thoroughly, and I might have input when I get a chance to use the ReactTable, but by my cursory analysis I think it's great. @oyvindberg I propose we merge the PR request.

**Comment by oyvindberg** [comment]
Alright, I finally had some time to check this out, very much sorry for the long delay @atooni .
This is good work, the react table is looking better and better :)

However, there is one problem with the implementation. It was already there from before, but with the extraction of `ReactTableRow` into its own component it is much worse still. When we use the `ScalaComponent` builder and say `build`, we actually create a new react component. That primarily means that react will always rerender everything, so performance will be bad.

This is one of the things i still havent seen a good solution for in scalajs-react, except for building the components in a static place (in an `object`, typically) for `Any`, and then casting to the current `T`.

Do you feel like having a look at fixing that?

**Comment by atooni** [comment]
Hi, 
no worries - I know the feeling to be split between projects. I understand your remarks regarding performance and it is definitely on my list. Right now I have to finish some work on the application that is actually using the components and I am using a local build for that, which is fine for the moment. 

We are about to start testing against larger datasets and there are some things that definitely need improvement. If you are fine to leave the request open for now, I can have a look over the next 2 weeks or so. 

Are you thinking along the lines to create the sub components only once and then reuse them in the views ? - In that case we might need to have a look at how we want to react to changes in the underlying dataset.

**Comment by atooni** [comment]
Hi, 
we needed some time to work on our container infrastructure itself. Therefore we are coming back to the UI just now. I am keen to review the table changes I have made a couple of months ago and get this merged if possible. I will be working on this for this and next week and see how far i get. 

Best regards 
Andreas

**Comment by rleibman** [comment]
Hey... we're moving the official repo to https://github.com/scalajs-react-components/scalajs-react-components
The current working branch is 1.1.0. 
I really want your changes in but I want to make sure we're all up to the latest, and there's a LOT of changes since you started. Would you mind taking a look and see how your changes work with the 1.1.0 branch and creating a pull request there? I **promise** I'll merge it right away.

**Comment by atooni** [comment]
Hi, 

it has been a while since we were working on our UI. There is some more work for me on the backend, but then finishing the UI is on my schedule. This having said, it will be prabably 1-2 weeks before I can look at it again.

**Comment by atooni** [comment]
Wow, has been ages since I have worked on this. Seems to be a lot of changes.

**Pull request closed without merging**
