### PR TITLE
Material ui 0.13

### PR DESCRIPTION
**Pull request by oyvindberg**
So, a lot of goodies here - we now have a bunch of new components. Most notably cards, grids and tables, and the new menus. All of this is very little tested - we should really write more tests/demos!

The layout of the facades is not set in stone yet, im still working a bit on that. my hope is to get them as close to the previous ones as possible, though there are a bit of api breakage anyway.

### CODE REVIEW

**Comment by chandu0101** [comment]
comments for props :+1:  :+1:  :+1: 

by hand or some automation ?

**Comment by oyvindberg** [comment]
it's 95% automated. i was brave enough to generate the wrappers based on the material-ui documentation with a mechanism for inferring/overriding types.

**Comment by chandu0101** [comment]
cool , btw this PR has scalajs-react 0.10 upgrade code also right ?  no need to worry about #31 .. ?

**Comment by oyvindberg** [comment]
i will merge #31 now i guess, havent found any big problems with ti

**Comment by chandu0101** [comment]
cool go a head ,merge all and please update change log and let me know i'll publish artifacts :)

**Comment by oyvindberg** [comment]
I'm saying good enough for now. One demo is not working, and one component needs to be updated. marked both as broken and removed from demo for now - will get to that.. soon.

There will inevitable be some breakage with material-ui, but we need some feedback to find all of that. merging this too

**Pull request merged**
