### PR TITLE
* added mobile events

### PR DESCRIPTION
**Pull request by coreyauger**
- added mobile events: onTouchStart, onTouchEnd that call the onMouseDown, onMouseUp handlers.

### CODE REVIEW

**Comment by chandu0101** [comment]
nice :+1:

**Comment by coreyauger** [comment]
I should be able to contribute more as I start to use more of the components.. really great work man.. keep it up!

**Comment by coreyauger** [comment]
There has been a few more issues regarding mobile events on a few devices... specifically how things are handled in DomUtil.  It seems like the 

``` scala
def isTouchDevice = dom.window.hasOwnProperty("ontouchstart") || dom.window.hasOwnProperty("onmsgesturechange")
```

Is not supported across all devices.  However.. there is a way to get the "type" of event through the e.type string.  I have modified the 

``` scala
def dragEventFor(name : String) =  ...
```

To have an overload of the following

``` scala
def dragEventFor(e:Event, name : String) = name match {
    case "start" => if (e.`type`.contains("touch")) "touchstart" else "mousedown"
    case "move" => if (e.`type`.contains("touch")) "touchmove" else "mousemove"
    case "end" => if (e.`type`.contains("touch")) "touchend" else "mouseup"
    case _ => ""
  }
```

But this would require modifying code that uses this function... it may be possible to have an implicit parameter that would get around this.. I wanted to stop and see what your thoughts are before I modify and make a PR.

Thanks.

**Comment by chandu0101** [comment]
feel free to modify the code ,btw  its scala port of https://github.com/mzabriskie/react-draggable ,i forgot to add in comments ;)

**Comment by coreyauger** [comment]
Ok I will find a reasonable modification and submit a PR.  Thanks!

**Pull request merged**
