### PR TITLE
Upgrade to scalajs-react 1.0.1

### PR DESCRIPTION
**Pull request by fmcgough**

### CODE REVIEW

**Comment by oyvindberg** [comment]
Wow! Fantastic effort there @fmcgough! Thanks a lot!

So we have one problem, which is that @rleibman has been working on this for a while, and that branch is almost mergeable. I apologize for us not having created a visible PR for that, we have just kept it on gitter.

I'm also deep in the Caucasus without a computer these days , so it's hard for me to do QA and/or merge these branches for another two plus weeks.

I'm thinking that we merge this (given that most things work, which I cannot check right now), and then I or @rleibman rebase that branch on top of this, and merge both. Our main changes, apart from the upgrade, is to inline and update the generator for mui/sui/eui, so it's not like all the changes are in conflict. Also it will be super useful to see that we ended up with the same types.

Do you consider that a good way of proceeding, @rleibman ?

**Comment by rleibman** [comment]
<sigh> This is going to be painful :( I'm back from vacation today, but got tons of real work I need to catch up with. When are you back from your holiday? 
Yes, if @fmcgough's stuff works we can merge it, and then merge it with our branch, but I hope we can work together to see what the differences are and which ones we want to keep, there is lots of work to do! However, I'm very excited at seeing a third pair of eyes trying to attack the problem, particularly on the common (i.e. non-generated) code.

**Comment by fmcgough** [comment]
Thanks, sorry I didn't think to check the gitter channel! I was after using this for a personal project so thought I'd just go ahead and upgrade it. I didn't really do much with the generators other than get things to compile, I'm more comfortable using vim macros than scala ones to generate code 😅 

I've tested all the bits of the demo site, so I'm fairly confident about those, but there may well be some bits that don't have demos that I've missed - if you can point me towards any of them I can have a poke about. Let me know if I can help with reviewing and merging the other branch too.

**Comment by oyvindberg** [comment]
So I've had a good look now, @fmcgough .

Like my comment from a few weeks back, i still intend to merge this more or less as-is, and probably do a release of it as well. I hope you will pardon me, but i had to rebase your branch on a scalafmt-formatted version of master, to make the big merge with the other PR possible. This means i will close this PR, and merge it manually. Will make sure to keep your blame lines :)

still loads of thanks for your work here.

**Comment by fmcgough** [comment]
Sounds good to me, cheers :)

**Comment by workingDog** [comment]
thanks for this great library. 
I'm eagerly waiting for the upgrade, which may as well be for scalajs-react 1.1.0.

**Comment by atooni** [comment]
Hi, I have used the upgrade-1.0.1 already together with 1.1.0 and everything seems to work so far. For now I am building the stuff locally to include it in our project. 

Great library, BTW !

**Comment by oyvindberg** [comment]
Alright everybody. I just merged this (outside of this PR, as mentioned above), and am releasing 0.7.0 as we speak. Thanks for the great work @fmcgough . Please try it out @atooni, @workingDog :)

**Pull request closed without merging**
