### PR TITLE
Allow MuiAvatar to display a character instead of an icon

### PR DESCRIPTION
**Pull request by codingismy11to7**

### CODE REVIEW

**Comment by oyvindberg** [comment]
Thanks!

I see the prop type for the component is 
`children: React.PropTypes.node` - so i suppose the parameter really should be
`child: js.UndefOr[ReactNode]`?

**Comment by oyvindberg** [comment]
Or well, if it only works with one letter anyway i guess the the type might be fine. how general is this?

**Comment by codingismy11to7** [comment]
sorry, busy time of year and i just saw this. anyway, i'm sure the components could successfully consume more general types than this, yes, but really - it's either provide an icon, or give it a character. i thought the character was the more useful type.

**Comment by codingismy11to7** [comment]
thanks for merging

**Comment by oyvindberg** [comment]
Ah yeah, i know everything about busy here :)

I changed it afterwards to `ReactNode`, because you can both give it icons or longer strings as a child

**Comment by codingismy11to7** [comment]
so, i'm all about following the underlying functionality, so i'm great with this checkin. thanks for accepting. however - would it be more useful to keep the character type? i mean, icons can already be provided through arguments to the case class. it's only in the case that you want a _text_ icon that you pass in a child, and in that case it only displays one character. so `js.UndefOr[Char ]` gives a better-typed interface to the documentation, while accepting a `ReactNode` gives a better-typed interface to the behavior.

either way, i'm great, and following the behavior is probably better. but one reason to use SJS and typed languages in general is that the compiler checks your code for you, and if you want to send in an icon you do it through the case class, and if you want to send in a character to display in the avatar, you do it through the child. just one way we could actually _improve_ the interface when using the SJS library over the ambiguity of the untyped JS stuff.

**Comment by codingismy11to7** [comment]
actually, i never tested more than one character. it may display more. one seems to be the only useful amount, but maybe if it displays more characters in a sensible manner then accepting a string or reactnode is better.

thanks

**Pull request merged**
